# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# Offense count: 108
Metrics/AbcSize:
  Max: 298

# Offense count: 53
Metrics/BlockNesting:
  Max: 8

# Offense count: 14
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 2000 # WOW!

# Offense count: 106
Metrics/CyclomaticComplexity:
  Max: 71

# Offense count: 136
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 440 # WOW!

# Offense count: 3
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 428

# Offense count: 8
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 11

# Offense count: 98
Metrics/PerceivedComplexity:
  Max: 90

Metrics/BlockLength:
  Exclude:
    # rspec DSL contain huge blocks
    - "test/**/*.rb"
  Max: 150 # some UI loops are huge

# Offense count: 8
Lint/Loop:
  Exclude:
    - 'src/clients/sw_single.rb'
    - 'src/include/packager/key_manager_dialogs.rb'
    - 'src/lib/packager/clients/repositories.rb'
    - 'src/modules/InstShowInfo.rb'

# Offense count: 3
Naming/AccessorMethodName:
  Exclude:
    - 'src/modules/SourceManager.rb'
    - 'src/modules/SpaceCalculation.rb'

# Offense count: 17
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts.
Naming/FileName:
  Enabled: false

# Offense count: 473
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Enabled: false

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'src/modules/Packages.rb'

# Offense count: 148
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Enabled: false

# Offense count: 10
# Configuration parameters: SupportedStyles.
# SupportedStyles: snake_case, normalcase, non_integer
Naming/VariableNumber:
  Enabled: false

# needs more testing before enabled
Style/FrozenStringLiteralComment:
  Enabled: false

# needs more testing to replace all URI.escape calls. Ideally own class for libzypp path
Lint/UriEscapeUnescape:
  Enabled: false
