#! /bin/sh
tmpdir=$1
echo "# /var/lib/YaST/update.inf -- (c) 2002 Suse Linux AG" 						>/var/lib/YaST/update.inf
echo "#" 												>>/var/lib/YaST/update.inf
echo " " 												>>/var/lib/YaST/update.inf
grep DIST_IDENT $tmpdir/info |  sed  -e 's/DIST_IDENT.*\(SuSE.*\)/Basesystem:           \1/' 		>>/var/lib/YaST/update.inf
grep DIST_IDENT $tmpdir/info |  sed  -e 's/DIST_IDENT.*\(SuSE.*\)-\(.*\)\#\(.*\)/Distribution_Name:    \1/' >>/var/lib/YaST/update.inf
grep DIST_IDENT $tmpdir/info |  sed  -e 's/DIST_IDENT.*\(SuSE.*\)-\(.*\)\#\(.*\)/Distribution_Version: \2/' >>/var/lib/YaST/update.inf
grep DIST_IDENT $tmpdir/info |  sed  -e 's/DIST_IDENT.*\(SuSE.*\)-\(.*\)\#\(.*\)/Distribution_Release: \3/' >>/var/lib/YaST/update.inf
grep -v ^\# $tmpdir/update.in_ | grep -v DefaultSrcPatchMedium >>/var/lib/YaST/update.inf
